### ISSUE TITLE
Uses deprecated iteritems() function for dictionaries

### ISSUE THREAD

**Issue by batson** [chanzuckerberg/idseq-cli#23]
the cli fails with python 3.6. `.items()` is the new way to iterate. suggested solutions [here](http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items).

an example error:

line 68, in clean_samples2files

    `return {k: sorted(v) for k, v in samples2files.iteritems() if len(v) in [1, 2]}`

**Comment by tfrcarvalho** [comment]
Fixed #31
