### ISSUE TITLE
Error: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by tbigot** [chanzuckerberg/idseq-cli#42]
The splitting process fails to finish with error 

```py
Error: sequence item 0: expected str instance, bytes found
```

It occurs where the method `parts` returns 
```py
subprocess.check_output(
                "ls {}*".format(part_prefix), shell=True).splitlines()
```

Indeed the results of this is a byte string as you can see here (printing the result of the command before returning it):
```py
[b'./s1.fastq__AWS-MULTI-PART-aa', b'./s1.fastq__AWS-MULTI-PART-ab', b'./s1.fastq__AWS-MULTI-PART-ac', b'./s1.fastq__AWS-MULTI-PART-ad', b'./s1.fastq__AWS-MULTI-PART-ae']
```

The problem is when the return of this method is used with `join` here:
```py
"parts":
     ", ".join(f.parts(max_part_size)),
```
knowing that `join` cannot work with a byte string.

It is solved by replacing 
```py
subprocess.check_output(
                "ls {}*".format(part_prefix), shell=True).splitlines()
```
by
```py
subprocess.check_output(
                "ls {}*".format(part_prefix), shell=True).decode("ascii").splitlines()
```

This issue could be related to:
*  my python version: Python 3.6.0
*  my locale: `fr_FR.UTF-8`

Thanks in advance!

**Comment by jshoe** [comment]
Thanks for reporting @tbigot, much appreciated!
