### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by dcastaneda5** [chanzuckerberg/idseq-cli#57]
Hi! I am having this problem whenever I try to run idseq in bulk mode. I've been thinking, and if I am not mistaken IDseq was designed for illumina sequencing platforms, correct? My data comes from nanopore, could that be the problem?

Thanks,

Daniel

**Comment by jshoe** [comment]
Hi @dcastaneda5 , sorry, we don't monitor this page regularly. Please email help@idseq.net and we can help you out, thanks! (However, the error message is likely a bug. Are you on the latest version of idseq-cli?)

**Comment by cdebourcy** [comment]
Hi @dcastaneda5, we have fixed the bug (https://github.com/chanzuckerberg/idseq-cli/pull/59). Please upgrade your installation of idseq-cli to the latest version and try again, and do let us know if there are any additional issues. Thank you for reporting!
